### ISSUE TITLE
Consider changing the converter and entity matcher to not fail fast and return error counts

### ISSUE THREAD

**Issue by arian487** [Recidiviz/recidiviz-data#1094]
Currently, this has to happen by the caller but we can consider having them handle it internally and returning the total errors in addition to the matched/converted entities so the parent caller doesn't need to wrap everything in try/catch.

**Comment by zacharylawrence** [comment]
For what it's worth, my first thought on this would be to isolate the logic in the converter/matcher to divorce and "how to convert" logic from the "how to handle an exception" logic.

For example:
```
converter = Converter(ingest_info)
for person in ingest_info.people:
  try:
    entity_person = converter.convert(person)
  catch ...
```
or
```
entity_matcher = EntityMatcher(scraped_entities)
entity_matcher.match_all()  # This makes 1 call to the database and ensures we match all people
while(
  try:
    matched_entity = entity_matcher.next()  # If entity matching had an exception, it will wait to throw it here
  catch ...
```

**Comment by terinpw** [comment]
chatted with @arian487 

in #1284, we move error counting into the entity matcher as opposed to relying on the persistence layer to call match on individual people and then catch the errors. We did this because entity matching is only valid if we attempt to match all people, and therefore it shouldn't be up to the caller to match people one at a time. For this reason, the entity matcher now matches people and counts the # of errors it encountered during this process. 

For the converter, we decided still have the converter fail fast because a) it can convert individual people fine, and b) we break out the thrown EnumConversionErrors into a few error counters (protected class errors or non protected class errors). This parsing of errors into separate counters makes more sense for the caller to perform.
