### ISSUE TITLE
Add a robust method for detecting when the end of the us_ny roster has been reached.

### ISSUE THREAD

**Issue by ghost** [Recidiviz/recidiviz-data#113]
Right now UsNyScraper.results_parsing_failure() looks for a hard-coded string literal 'ZYT' as the first three letters of the last name to detect when the end of the roster is reached. Develop a method that does not depend on any particular value being the last entry in the roster.

**Comment by ageiduschek** [comment]
@jessex @ohinds - I played around a little with the search results. Here are my thoughts on how we can fix this:

1) There's big red text that says "NO MORE NAMES ON FILE" when you get to the last page of names. We could just check for this text and terminate a scrape when we see it. Pros: this is obviously the termination condition. Checking before we fail to parse will probably be easier to read. Cons: This breaks with copy changes or if they take away the label.
2) Rather than blindly trying to parse the next page, check to see if it might be the search page. When we start the crawl, we can find the title of the search page, pass that as a param to our search results scrape, and keep checking for that title to show up again. Pros: Resilient to even copy changes in search page. Cons: Will break if they change the "next with nothing left" behavior to do something other than kick us to the search page.
3) Do both?? Look for the label and then expect clicking "next" to kick us to the search page once we've seen it. If either happens we terminate, but log an error if we don't see both? Pros: We will probably terminate at the correct time. Cons: more complicated.

Could use some input, especially re: how often we expect minor elements of this site to change.

**Comment by jessex** [comment]
Thanks for the investigation, @ageiduschek!
1. Looking at the final result page, I see that the text doesn't have any particularly helpful CSS selector to key on. It's just a `<p class="err">`. That means we'd be looking for either the `err` class, which could be used in myriad other ways, or the element with the text itself, which could be brittle, though certainly less brittle than the current approach.
2. This seems less brittle than the first one to me. I would expect that these sites see changes on the order of every couple of years, and that the changes are more typically cosmetic than flow-related. I tried gathering real data on update frequency from the [Wayback Machine](https://web.archive.org/details/http://nysdoccslookup.doccs.ny.gov/GCA00P00/WIQ3/WINQ130) but was unable to determine which crawls may correspond to actual page updates. Minus some styling differences, the form for the [earliest](https://web.archive.org/web/20120107201450/http://nysdoccslookup.doccs.ny.gov/GCA00P00/WIQ3/WINQ130) crawl of the site _looks_ identical. 
3. I think our system should be designed with multiple failsafes at critical branching points, so I concur with the idea of doing both of the above, if we don't have any other mechanism which looks more resilient. Looking around a bit myself, I think these two are our best bet for now.

**Comment by ageiduschek** [comment]
Ok then 3 it is :-)

**Comment by jessex** [comment]
Has this been solved in the updated NY scraper, @ohinds?
