### ISSUE TITLE
Snapshots should only save nested fields if they have changed since the last scrape

### ISSUE THREAD

**Issue by ohinds-vera** [Recidiviz/recidiviz-data#123]
Currently, `compare_and_set_snapshot` correctly computes differences between snapshot and an old record for scalar fields only. It should also store only fields that have changed between scrapes in more complicated fields such as objects, sequences, and sequences of objects. For example, currently the Record object has a list of 'Offense' objects, and `compare_and_set_snapshot` stores the entire list of offenses if any field in any offense has changed since the last scrape.

**Comment by ageiduschek** [comment]
When investigating this issue I realized that the approach outlined in this task doesn't handle what might happen if an offense is deleted.

From discussion with @jessex:

> We definitely want to track that the removal occurred. Expunging of an offense is one possibility, and there could be sentencing-related ones in the future when we start to ingest systems that separate out, for example, concurrent sentences. As it stands, there is no strict use case for doing any processing with the knowledge that a sub-entity array had an element removed right now, but it's almost certain to come up at some point, and when new ways of looking at criminal justice records come up they tend to be surprising. So we should think about this one now.

> The latest and greatest state of the data is recorded via the top-level Record, but we do want to be able to compare a series of Snapshots to see that some sub-entity was removed.
> * Storing a different sub-entity on the Snapshot (i.e. instead of Snapshot.offenses to match Record.offenses, we'd have Snapshot.offense_changes) that includes a flag like `is_deletion` is technically possible but messy, and makes conversion between Records and Snapshots more difficult because of an extra, nested layer of transformation to perform.
> * A similar approach would be to continue to track Snapshot.offenses but also track Snapshot.offense_removals, which would be an array of removed offenses. It would be easy to work with in the future by doing a simple check on whether Snapshot.offense_removals is empty. Conversion between Records and Snapshots stays straight-forward, but we have the added complexity of including an extra field on the Snapshot for any array sub-entity where removal is possible. 
> * Or, we scrap this plan and just resolve to always store an entire field whenever it changes, where it's a flat field, an array field, or an object field. That way, evaluation of a series of consecutive snapshots is predictable for all fields (compare the entire field in each snapshot, no matter what). It's more consistent from the perspective of the Snapshot field, but less consistent from the perspective of the lowest-level field available, i.e. sub-fields. It has less complexity overall than the other two, but inflates the amount of data we need to store and process as we navigate the object graph in some cases.

We decided that the best plan of action was to do nothing, since it's the simplest and least error-prone right now.

One idea though:
We could do is take advantage of the fact that Polymodel supports multiple inheritance (it does, right??). We can have our Snapshot (perhaps now more aptly called PersonRecordUpdate) mirror all the fields in Person and Record with same names and everything, but have all the types be hybrid types that extend from both the original type and a new Update record type which denotes the change type (add, delete, changed).
