### ISSUE TITLE
names_file should be optional in regions.yaml

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/recidiviz-data#169]
Currently the scraper will fail if it is not provided

**Comment by jessex** [comment]
[As discussed here](https://github.com/Recidiviz/recidiviz-data/pull/168#discussion_r231286568), we also need to make sure that `scraper_utils.generate_id` incorporates the region code in the conflict check. Right now, it checks Datastore to see if the 10-character id is unique, but that doesn't take into account the region code we expect prepended to the front. Having that code on the front should also make it a faster check, I would think, but it's still unnecessarily expensive.

**Comment by ohinds** [comment]
Just remove all the names file references.

**Comment by arian487** [comment]
Is there anything stopping us from removing names_file completely

**Comment by jessex** [comment]
Do we have a replacement concept yet for the use case of sites where we have to concretely (e.g. not-fuzzy) match on names to scrape data? If not, names files are still necessary in some cases.

**Comment by ohinds** [comment]
I think "making it optional" and "removing it completely" are fairly similar, because we support arbitrary keys in the region manifest. If a region needs a names file it can be provided. The difference is just passing the target list through to the scraper. But maybe it's ok at this point for the names file reading and writing to be handled internally to region scrapers. When we encounter multiple regions that need this, then we could extract this into a util.

**Comment by jessex** [comment]
>When we encounter multiple regions that need this, then we could extract this into a util.

I like this statement in general, but in this particular case the util already exists and it would seem to be more work to remove it with the idea that we may add it back later. "Making it optional" is a simpler route towards what we're after here.
