### ISSUE TITLE
Add lightweight UI to start, view progress, and stop scrapers

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/recidiviz-data#2]
As simple as:

```
Region    Last run      Status                          Actions

us_ny     10/21/2017    Completed                       [Start]
us_fl     10/21/2017    Completed                       [Start]
us_fed    In Progess    [-----------------R        ]    [Stop]
```

With the 'R' blinking, as the first letter of the inmate surname most recently stored for that region.

'Stop' is the main reason to have this page - currently starting a scraper is as easy as visiting a URL, and stopping it scraper means going into the GAE console and manually purging the TaskQueue for that scraper. `cron` should handle starting tasks eventually, but monitoring and stopping them should be easier.

Both of these should be actions on a web page, not based on our visiting a particular URL.

**Comment by jessex** [comment]
How do we feel about this one at this point? Are we happy with the tooling provided in GCP or would we still want some basic UI? The only thing that the Task Queue view in GCP doesn't seem to provide is a quick look at relative progress, e.g. place in the alphabet, but it is easy to spot check in the logs. It would also be possible to track a specific log message (the one which says that we just persisted a record for a particular name) so that a quick check would show you, for a given region/scraper, the most recent persisted record.

**Comment by arian487** [comment]
closing in favour of #408
