### ISSUE TITLE
can a person have multiple open bookings?

### ISSUE THREAD

**Issue by jamwalla** [Recidiviz/recidiviz-data#318]

**Comment by jessex** [comment]
Anecdote: someone once told me a story about a person who was on parole for two separate counties simultaneously. Community supervision is something we need to think about more thoroughly in our schema (+CC @arian487, @ohinds, @zdg2102, who were discussing this and prisons), and this _might_ be relevant, though it seems super rare. I suppose it could also be possible to have two separate open bookings if you were under investigation for separate arrests (in one or multiple counties), and being held in only one location on account of the laws of physics.

**Comment by zdg2102** [comment]
Because we're not doing cross-county person matching, I believe in all these cases mentioned, the person would be treated as 2 separate people, one for each region that is dealing with them. Unless we start doing cross-county matching, the only case of multiple bookings we would need to be concerned with is a person somehow having more than one open booking with a single county, which I can't think why it would ever occur.

**Comment by jessex** [comment]
@ohinds can comment on the likelihood of this, but I could see a person being investigated for two separate arrests in the same county, and these being modeled in some places as two separate bookings that are simultaneously active.

**Comment by zdg2102** [comment]
I'd have to defer to ohinds@, but I imagine that type of situation would be rare enough that I'd be comfortable just letting the system treat that case as 2 different people (unless they have a shared unique identifier, in which case that's going to be a real pain).

**Comment by ohinds** [comment]
I agree with @zdg2102 that this should be rare enough to ignore. Let's revisit this if we see if happening a lot.
