### ISSUE TITLE
Booking.person_id doesn't point to a valid Person in test_db

### ISSUE THREAD

**Issue by terinpw** [Recidiviz/recidiviz-data#376]
In our test db, there is currently a booking (booking_id=1) with a person_id = 194. But person 194 doesn't exist in our Person table. 

Not sure if you did manually editing - otherwise I'm confused as to how/why this happened.

**Comment by zdg2102** [comment]
Yeah, I'm pretty confident this is an artifact of when I was deleting all the old rows before we kicked off the most recent run. I probably cleared the booking table, this person/booking pair got written, and then I cleared the person table.

Is it messing up new writes? I can delete it if you need, otherwise I think we can probably just ignore it until we clear the tables again before the next run.

**Comment by arian487** [comment]
This is obsolete the database was just being messed with manually.
