### ISSUE TITLE
Properly handle unknown charge class

### ISSUE THREAD

**Issue by arian487** [Recidiviz/recidiviz-data#387]
Some sites have charge class = Unknown which is not currently mapped, how should we handle this?

**Comment by jamwalla** [comment]
Sorry if we've been over this before - do we care about the difference between UNKNOWN and OTHER? NY DOC lists OTHER alongside other race categories, which seems like the Hendry case, since they do list some race categories but don't know how to classify some people. This could be distinct from the way we handle 'Hispanic' as a race, where we set 'ethnicity' and leave race as blank (i.e. UNKNOWN).

**Comment by zdg2102** [comment]
Resolved with #504
