### ISSUE TITLE
Investigate date off-by-ones

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/recidiviz-data#50]
Example: DIN #83A6604

Date logic seems to be removing a day from everything. E.g., in the example above all date fields are one day earlier in our records than in the actual DOCCS record. They also have false-precision in terms of time of day, which may be indicative of the bug.

**Comment by cawarren** [comment]
Looked into this, as suspected it's timezones. Records are consistently off by 4hrs if the date is in the wintertime (EST = UTC-4), or by 5hrs if in the summer (EDT = UTC-5).

GAE operates in UTC (https://goo.gl/vJkwWZ), and unfortunately even the DateProperty ends up storing the time as well (defaulting to 00:00:00, specifically).

The question now is what to do about it, which isn't quite as simple as it seems on the surface. Some options:

**Option 1: Offset times to account for timezone**
- After scraper parses the date, assign the datetime value its local timezone, accommodating for DST.
- Convert that datetime to UTC
- Store in UTC

**Option 2: Store dates without tz info, as the correct date but in UTC**
- No changes

**Option 3: Store days as noon, local timezone**
- After scraper parses the date, assign the datetime value its local timezone, accommodating for DST
- Change time on timestamp to 12noon (in local time) (not yet sure we can change the time stored, for DateProperty - may end up meaning migrating those fields to new DateTimeProperty's)
- Convert datetime to UTC, store it.
- Migration path may just be to update the bg scraper and rescraper; should overwrite current times on the next pass. 

**Issues:**
- Option 1 is accurate as a day of the year, but will complicate any metrics
  - Calculation and querying logic will have to account for timezones in all cases
  - If they don't, cohorts across timezones may turn out to be off by days (10/10/2010-00:00:00 in NY is 10/9/2010 in CA), months (12/1/2010 --> 11/31/2010), or even years (1/1/2015 --> 12/31/2014).
  - The work needed in calculation / analytics logic would involve reading a datetime, determining the correct timezone and DST status for the relevant date. Assume there's solid library support for this.
- Option 2 allows for accurate comparisons, but individual data is inaccurate on inspection (similar to what led to filing this bug) and would require additional work to translate back to local time / 'the actual date' if needed.
- Option 3 may retain the best properties of the above. Datastore remains as accurate as possible, but times are set to noon on the correct day to minimize likelihood of analyses flubbing the conversions during comparisons. All US timezones are within 12hrs of UTC (Hawaii is UTC-10), and as a result even with wonky timezone problems during analysis any comparisons are likely to remain accurate.

Currently leaning towards Option 3. @jessex any thoughts? Is there an established way to handle this sort of thing?

**Comment by jessex** [comment]
TKTKTK

There is actually a standard convention for handling these sorts of issues in time zone handling: use an entity type that doesn't account for times, but only for dates. In fact, _none_ of the fields coming in from the DOCCS dataset include time-level precision. Only date-level precision. And the core models, e.g. `Inmate` and `Record`, correspondingly use `ndb.DateProperty()` instead of `ndb.DateTimeProperty()`. If those fields, such as `record.custody_date`, are being rendered up to time precision (which they are), then I think it is possibly because we are returning the Python `DateTime` type when we are [parsing date strings](https://github.com/Recidiviz/recidiviz-data/blob/d8a588ffd5d9674be5e670ee51521197f4e5e375/scraper/us_ny/us_ny_scraper.py#L1306). 

Then, presumably, NDB is "smartly" adding time-level precision to the `ndb.DateProperty` and turning it, effectively, into an `ndb.DateTimeProperty`. That last part is speculative and I haven't dug into NDB docs, but it feels like what's happening to me.

I would test this locally by changing the `parse_date_string` logic to return a `Date` instead of a `DateTime` and then see if the dates are stored correctly, sans time.

**Comment by cawarren** [comment]
Tested this by using Python's `datetime.date()` on the result of `dateutil.parser` in `parse_date_string` before storing the results of that method - browsing entities in datastore still shows an associated time (00:00:00 UTC).

I also see a note in the docs for GAE's [DateProperty](https://cloud.google.com/appengine/docs/standard/python/datastore/typesandpropertyclasses#DateProperty), it says:

> A date without a time of day; see DateTimeProperty for more information.
> 
> Value type: datetime.date; converted internally to datetime.datetime

I don't quite grok how those two lines reconcile.

**Comment by cawarren** [comment]
Verified that on read, entries contain a date object (not a datetime). 

Closing this as WAI. I'll still update the `parse_date_string` method to just try to store a date object, so that the mismatch doesn't throw off the inmate snapshot vs inmate record comparison in the rescrape CL.

**Comment by jessex** [comment]
Thanks for the investigation on this. So to make sure I understand, you're going to change `parse_date_string` to return a `Date` instead of a `DateTime`, but Datastore will still show a time component of 00:00:00 UTC, with the correct date component?
