### ISSUE TITLE
Refactor scraper setup() call to be us_ny specific, not general scraper interface

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/recidiviz-data#85]
_This is part of ingest generalization work_

Background:
Some scrapers may require certain work to be done before starting or resuming a scraping session, e.g. fetching session cookies from the site that's being scraped.

Currently, this is an expected scraper interface and `queue_control` (soon to be `scraper_control`) calls it directly before starting/resuming a scraper. Since this won't apply to all scrapers, however, and since its logic is scraper-specific regardless, this should not be a required scraper interface - it should be something local to each scraper, if needed at all.

Scope of work:
- Remove references to `scraper.setup()` in `queue_control` (/`scraper_control`)
- Update `us_ny` scraper to call its own `setup()` method from its `start` or `resume` functions, rather than expecting this to be called elsewhere.

**Comment by jessex** [comment]
@cawarren: curious to get your thoughts on this:

After digging through the code, I'm feeling a bit skeptical about taking this method out of the interface. A few reasons from the abstract to the concrete:
* Having `setup` and/or `teardown` methods on IO interfaces (which our scrapers are) is fairly conventional, especially when you're dealing with shared state that you need some level of sychronization in handling between invocations of that interface
* While it's true that not all scrapers will require it, it's true that at least one does now and more will in the future. In a world where, say, 50% of scrapers required setup, I would probably opt to have the other 50% allow this method to be a no-op, than to reimplement the pattern (small though it may be) of invoking a setup procedure at the beginning of start and resume calls in 50%
* In this particular case, I'm a bit nervous about the order of operations in terms of session and docket management. More below:

`queue_control.ScraperStart.get` includes the following:
```python
# Set up scraper for new session
scraper.setup(scrape_type)

# Clear prior query docket for this scrape type and add new items
purge_query_docket(region, scrape_type)
load_target_list(scrape_type, region, params)
```

So today, in the New York case, it marks any open us_ny sessions as closed and only once that's done does it purge the docket, which includes finding relevant sessions and clearing the `docket_item` on the entity. Because those sessions have already been closed, there's no chance that a scraper task will continue to operate on it after clearing the docker item. However, if we were to move the `setup` call back inside of the call to `start_scraper`, then the docket purge and its accompanying session modification would potentially happen to sessions which have not yet been closed. It's conceivable then that other code, say a scraper task that is unexpectedly running because of duplicate API calls or a failed previous attempt at stopping, would either rewrite that cleared docket item or have its own progress somehow corrupted because the docket item was changed on it in-flight. 

And while it may be true that because this happens only when starting new scrape pipelines we would expect there to be no issue, there are at least 9 different searches for _open_ sessions in the `us_ny_scraper.py` class and there's enough complexity in the system that it's difficult to stay with complete confidence that there's no chance the above edge case would occur. And stepping back into the abstract for a second, if we can conceive of other scrapers that would do similar session clearing in their own `setup` methods, then we can consider that this is a consideration for more than just the New York scraping system.

So given the potential for funky edge cases and what I see to be a relative harmlessness of including `setup` in the scraper interface, I would opt to keep it in the interface. Let me know if this seems like FUD or just wrongness to you.

**Comment by cawarren** [comment]
No, you make some very good points. My leaning towards devolving it back into the scraper was based on the fact that in `us_ny`, the `setup()` call had become slimmer and slimmer as refactorings moved a lot out of it.

Having this as a no-op in scrapers that don't need it, and be part of the general scraper interface, makes sense to me. Curious for @ohinds-vera's thoughts, since he's been working on broader Scraper abstraction.

**Comment by ohinds-vera** [comment]
I agree with @jessex that we can just have a stub in the superclass and override it when needed. 

Also, since the call to `setup()` happens in `queue_control.py` right after the scraper is created (or will be created when it's made into an object as part of #87), it would be nice if we could call it directly from the scraper superclass initializer. But we can't unless we can be sure it will never depend on things created in the child's initializer, unless we are sure that the parent's initializer will be invoked at the end of the child's. Sometimes I hate Python.

**Comment by jessex** [comment]
Let's keep this open for now until we get #87 in the books and we know how `setup` will be invoked and whether there's any change we want to make.
