### ISSUE TITLE
Pull out scraper as a class all scrapers inherit from

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/recidiviz-data#87]
_This is part of ingest generalization work_

Background:
Currently, the `us_ny` scraper is standalone - it doesn't inherit anything, and there's no common interface defined for scrapers to be used by the rest of the ingest system.

The design doc calls for a common Scraper superclass to be used to ensure consistent implementation and interfaces for scrapers, with stubs for those interfaces that must be implemented by inheritors.

From Josh's comment on issue #55 :

> Another technical point: we should likely be making use of Python Abstract Base Classes here. Check out the [PEP](https://www.python.org/dev/peps/pep-3119/) and the [module docs](https://docs.python.org/2/library/abc.html). I could see an interface around individual region scrapers to the effect of start, stop, and resume commands, and/or more fine-grained interfacing around navigation and parse functionality. We'll need to feel it out, but having a discrete "interface" for region scrapers to extend will provide much more in the way of structure and safety than our introspection-based model we have right now.

Scope of work:
- Read the documents described in issue #55, and the design doc [Scraper section](https://docs.google.com/document/d/11fv-hLwLOFcM5XSE16lYne5hnqFzcQK1vwvTBVVyhn8/edit#heading=h.90ynq2mmh781)
- Create a new `scraper` module under the `ingest` package (if issue #82 isn't finished yet, the package might still be called `scraper`) - see design doc [Modules section](https://docs.google.com/document/d/11fv-hLwLOFcM5XSE16lYne5hnqFzcQK1vwvTBVVyhn8/edit#heading=h.v6780khuazyt)
- In the new `scraper` module, create a scraper class that future scrapers will implement, with stubbed methods for start/stop/resume
- Update the `us_ny` scraper to use / inherit from the new `scraper` module
- Add relevant tests

**Comment by ohinds-vera** [comment]
@cawarren @jessex 

As I get around to the task spawning part of this work, I have some design decisions that it seems worthwhile to talk through here.  

Previously, all state was passed through params from one task function to the next. Now, we have an object where we could store this state. However, we don't have the option of traditional scoping, so we'd probably have to play some trick where we rebuild the object at the beginning of each task and pass around a pickled copy. This would have some advantages from a programming standpoint in that handling the data passed from task to task would be through a familiar mechanism (member variables). 

But the pickling and recreating the object between tasks seems inefficient. The other extreme is to make Ingest objects stateless and keep passing around state in the task params. This would still allow a lot of code reuse, but isn't as object-oriented. 

A third option is a slight compromise where we caould always keep a 'params' dict as the only dynamic member variable, and that could be set on task spawn based on the data passed through the task queue. 

Do you guys have preferences between these approaches, or other ideas?

**Comment by jessex** [comment]
Great question, @ohinds-vera. In my experience working with task queue systems and other systems with similar characteristics -- the launching of discrete processes with a variety of inputs that may vary from process to process -- there are two conventions:
* Pass in a flat mapping of key-value pairs which is deserialized into the worker's language's map structure (e.g. a `dict` in Python)
* Pass in a flat mapping of key-value pairs which is deserialized into some object that contains that mapping in addition to other fields and/or methods for convenience (e.g. a method that operates on multiple input fields to provide some output, or a constructor that validates the existence of required fields)

Data passed over the wire as input is typically not a serialized language-object but some well-known serialization format like json or protobuf. There are some downsides to pickling a Python object for serialization and deserialization, beyond what you've already laid out:
* All task creators must be Python processes so there's limited flexibility in terms of launch process,
* there can be pain in the event of a model change due to a lack of versioning, 
* it opens up a new attack surface as malicious actors could insert malicious code as input which gets executed on one of our workers, 
* it is less than ideal in terms of efficiency not only because of the absolute hit of pickling but because of the relatively low value (we would be incurring the overhead of pickling and unpickling once each on each launched task for a single object with a small number of simple fields as opposed to a large, complex object graph), and
* because different processes may eventually need different parameters, our object may need to permit dynamic parameters anyway, which reduces its value (but does not mitigate it entirely, in the event that there are still required parameters).

For all of that, I don't think we should use Pickling to produce our serialization format. I suggest we pass in params as a flat map and then convert that map into an object that we construct with fields if a) those fields are known, and b) there is enough value in typing and validation or other convenience methods that it outweighs the construction time. I would imagine simple object construction from known fields to incur a negligible memory and throughput hit, so the typing benefit alone may be enough to justify it. When one task launches another task, it would then pass the necessary unpacked fields from that object into the next task as a flat param map.

**Comment by ohinds-vera** [comment]
Thanks @jessex!  Sorry for the loose language, I wasn't meaning a literal python-specific pickle, but all those points are well taken. 

I like your proposal, perhaps I can cook something up where the child class defines the allowed fieldnames and they are automatically assigned from the task-provided param map in the super's constructor? 

This is going to result in a few members that are param maps themselves, which is slightly better than having to dig down into each param map. I don't really want to provide the machinery for nested members yet. Let's reevaluate if this scheme is found to be severely lacking?

**Comment by jessex** [comment]
Sounds great, Oliver. Let's go with that for now and evaluate in code
review.

**Comment by ohinds-vera** [comment]
I just ran into a name collision in the module imports. Now that I have to import something from the top-level 'models' module from a file in the top level of the 'ingest' module, the 'from models import env_vars' resolves to the 'models' module in the 'ingest' module, not the top level one. I'm going to have to rename 'ingest.models' to something else, maybe 'session'? Thoughts.

**Comment by cawarren** [comment]
Paging @jessex on this one

**Comment by ohinds-vera** [comment]
@jessex I messed about with this a fair bit and did find a solution, although i'm not sure it's preferable to enforcing a 'no sub packages named "models"' policy.  My solution was to create a 'recidiviz' directory in the repo root that contains all source code directories as well as an __init__.py. This creates a top level package so we can then import recidiviz.models from anywhere without ambiguity. This also has the pleasing side effect of making our imports read very much consistently with the google ones, BUT means a ton of moving around code. 

Happy to entertain other ideas if you have them!

**Comment by jessex** [comment]
I actually like that solution quite a bit and was interested in placing all of our source code into a directory at the root level named `recidiviz`. This is also aligned with recommendation from Kenneth Reitz, which we are trying to follow: https://www.kennethreitz.org/essays/repository-structure-and-python. As long as this works and we can run both ingest and calculation successfully locally (and deployed to GAE) then let's go with that route. We should do that in its own PR, though, because as you mention it is a large code shift.

**Comment by ohinds-vera** [comment]
@jessex great! I'll make an issue and do the refactor in a separate branch, then merge in this PR, as this one depends on the refactor.

**Comment by ohinds-vera** [comment]
PR #112 addressed this.
