### ISSUE TITLE
Split `region_maniest.yaml` into per-region files

### ISSUE THREAD

**Issue by ajsecord** [Recidiviz/recidiviz-data#942]
(Also see #943  for a similar thing with `cron.yaml` and `queue.yaml`.)

The global config file `region_manifest.yaml` is a regular source of merge conflicts for new scrapers. It will be tough to scale contributions beyond 1-2 contributors if every new scraper that gets submitted generates a merge conflict with all the other in-progress scraper pull requests.

The `region_manifest.yaml` file could be split into per-region files since we [own the code](https://github.com/Recidiviz/recidiviz-data/blob/cdd82e30e236430509a8f5dd8709d2fa57be9204/recidiviz/utils/regions.py#L163).

This feature request is to split the single `region_manifest.yaml` file into one YAML file per region, stored next to the region scraper's code, for example, `ingest/scrape/regions/us_in_boone`.

1.  Write a throw away script to break out the `region_manifest.yaml` into a one YAML file per region.
1.  Change the code in `utils/regions.py` to search `ingest/scrape/regions` and load all the YAML files.
1.  If performance isn't adequate (disk search instead of loading one file), decide on a caching strategy.
1.  Update documentation for new scrapers.

Keep the script from the first step until all in-progress scraper PRs have landed so authors can update their PRs while we're migrating.

**Comment by jessex** [comment]
This is something a few of us have discussed previously, including @arian487, and it's something I would love to see. Point 3 is the only area of uncertainty to me, and we'll solve that--otherwise I don't see a reason not to do this. In theory it's nice to have one big list of all of our supported regions, but at the file grows it becomes less useful as a human-readable manifest, and if that was a real use case we could always expose an API for aggregating and returning the manifest to human users.

**Comment by colincadams** [comment]
re: caching. Right now we load the entire manifest into memory on first access and then keep the whole thing cached for the lifetime of the instance. Worst case performance is still reading the manifest from disk, so I don't think this will have a performance impact. And with the manifest split up I think it will be more straightforward to expire cache entries if we decide this is taking up too much memory or to just read in the manifest for the regions we are running at that time.
