### ISSUE TITLE
Assemble `cron.yaml` and `queue.yaml` from per-region files to prevent merge conflicts

### ISSUE THREAD

**Issue by ajsecord** [Recidiviz/recidiviz-data#943]
(Also see #942 for a similar thing with `region_manifest.yaml`.)

The global config files `cron.yaml` and `queue.yaml` are regular sources of merge conflicts for new scrapers. It would be tough to scale contributions beyond 1-2 contributors if every new scraper generates a merge conflict with all in-progress scraper PRs.

It looks like `cron.yaml` and `queue.yaml` need to stay as single files, at least for deployment time. This feature request is to split these files into per-region YAML files and assemble the global `cron.yaml`/`queue.yaml` file at deployment time.

1.  Write a temporary script to split the global files into per-region files.
1.  Write a script to assemble each of the per-region files back into single global files. Test that the round-trip through the first two steps generates identical global files.
1.  Test with release engineer to double-check that the files still work for deployment.
1.  Delete global files from the git repo, add them to .gitignore.
1.  Update docs for scraper authors.

Keep the temp script from the first step until all in-flight scraper PRs can be updated.

**Comment by jessex** [comment]
I like the spirit of this, but ideally we wouldn't need `queue.yaml` and `cron.yaml` anymore. To that end, I believe @rasmi has a design that uses Cloud Composer to avert the need to manually cron every region and has also previously looked into completing our migration away from GAE Task Queues to Cloud Tasks by removing the `queue.yaml` manifest in favor of a more dynamic approach. Any thoughts on those conversations, Rasmi?

**Comment by colincadams** [comment]
Re: `queue.yaml`, I think moving to a generated `queue.yaml` is a good first step. Then we can have just the actually region-specific queue configuration defined in the region (i.e. qps), which we will need when we dynamically create the queues. This also gives us the ability to define sane defaults for values, so that regions don't have to specify every queue config value.

(with @arian487's recent `cron.yaml` change we should no longer have conflicts there.)
