### ISSUE TITLE
We should detect when a scrape session for a region is complete

### ISSUE THREAD

**Issue by ohinds** [Recidiviz/recidiviz-data#974]

**Comment by colincadams** [comment]
One possible idea for how to handle this:

We could keep a `pending_task_count` on the `session` object in datastore, and increment it by `tasks_added - 1` at the end of each scrape. When it hits zero we can call out to cloud composer that the scrape has finished, or trigger the next step another way.

I'm not sure that we can fully guarantee consistency between datastore and cloud tasks this way, e.g. our instance dies right after we decrement the count but before we return 200 so cloud tasks retries the task. Worth thinking about further whether there is a good solution to handle that.

**Comment by jessex** [comment]
Could we have a background process that polls a particular subscription path to check for the existence of messages for a given region? We'd want to be smart about it so we weren't querying for every single region repeatedly around the clock. For example, we could have a single background process that checks every, say, 10 minutes to find the list of regions that are currently active and compares it against the list from the previous check. If something dropped out then we can reason that it's no longer active, though there could be edge cases to think through there depending on the exact delivery semantics of Pub/Sub.

**Comment by colincadams** [comment]
My understanding of the docket (which admittedly isn't great even though I migrated it to pub/sub) is that for our typical background scrape, an item gets added to the docket on scraper start. This item is then immediately pulled and added to the session, but not acked, and then the scrape starts. AFAIK this docket item is never acked so is returned to the docket after 5 mins, but we also never pull from the docket again. Next time that scraper is started the docket is purged and a new item is added.

I think that part of the core of this problem is that we don't know when to ack the docket item either. I don't totally remember how us_ny used to use the docket, if we went back to a model like that would that make the solution easier?

**Comment by colincadams** [comment]
Now we could potentially query the cloud task queue for a given region to see if a scrape is done, assuming that query includes currently leased tasks. But this doesn't work in the model of shared queues without inspecting each message. I can look into that to see if it is possible.

**Comment by jessex** [comment]
>AFAIK this docket item is never acked so is returned to the docket after 5 mins

Never acking the docket item would be news to me. At least when the docket was a pull-queue, I was under the impression that it was acked by virtue of the task that pulled the item from the queue returning a 2XX-space response. I assumed that we had an equivalent mechanism in the migration to Pub/Sub?

>but we also never pull from the docket again.

This is basically true, yeah. To be complete: In the early days, background scraping would put a single item on the docket which would invoke more tasks that would be placed directly onto the scrape queue for the region. Snapshot scraping, on the other hand, would put many items on the docket, one for each person we wanted to check up on. We no longer have such a dichotomy thanks to the inferred release job. In total, yes, I think this particular fact shoots my docket idea in the foot.

>I can look into that to see if it is possible.

Let me know what you find! Another hand-wavy approach would be if we were generally able to know that a task we were queuing up would be the final task for a region when that task was created, regardless of regional navigation specifics, then we could set a flag on that task. But I don't think that's actually the case in all regions. Tracking via sessions might make the most sense, as you described it.

**Comment by colincadams** [comment]
Filed #1045 to continue docket related discussion.

Looping back on this. Regarding polling, it looks like we can [list all of the messages in a cloud task queue](https://cloud.google.com/tasks/docs/reference/rpc/google.cloud.tasks.v2beta3#google.cloud.tasks.v2beta3.CloudTasks.ListTasks). It is not totally clear whether currently leased tasks will show up in this, but my hope and belief is that they will. If so, I definitely think this is the way to go.

Otherwise, support for [transactions across datastore and cloud tasks is possible](https://cloud.google.com/appengine/docs/standard/python/datastore/transactions#transactional_task_enqueuing) at least for adding tasks, although it isn't clear how to use it with the new cloud tasks api. If the above solution won't work we could look into this further, although I still don't believe the acks can be transactional for push tasks. Our acks are implicit in returning a 2XX response code, so we could perform the datastore operation just before returning but I don't believe we could make them atomic with the ack.

**Comment by jessex** [comment]
Yeah I'm also skeptical that it could be made atomic, but it is perhaps the case that not-quite-exactly-once semantics would still be okay. To have any impact on proper detection of a completed scrape session, we'd need this rare transactionality failure to occur with the very last task of a given session, and the end-result would be the failure to launch any tasks reliant upon detecting the completion of that particular session for a particular day, which may not be terrible. If we could detect that the failure had occurred, we could alert on it and manually intervene.

Also, I thought I had read at some point that the transaction sharing between Datastore and Cloud Tasks had been removed in the latest Datastore/Firestore update, but I can't find any documentation suggesting that now on a quick search.
